name: gfwlist_auto
 
on:
  [push, workflow_dispatch]

jobs:
  sr_ge:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: sr
        run: ./auto_build_sr.sh
      - name: base64
        run: ./autoBase64.sh
