name: gfwlist_auto
 
on:
  [push, workflow_dispatch]

jobs:
  sr_ge:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: sr
        run: python3 shadowRocket.py
      - name: base64
        run: openssl base64 -in gfwlist_raw.txt | tr -d '\r' > gfwlist.txt
      - name: git
        env:
          GHA_DEPLOY_KEY: ${{ secrets.GHA_DEPLOY_KEY }}
        run: |
         git add .
         git config --local user.email "972161836@qq.com"
         git config --local user.name "buzhangjiuzhou"
         git commit -a -m "update"
         git remote set-url origin "$(git config --get remote.origin.url | sed 's#http.*com/#git@github.com:#g')"
         eval `ssh-agent -t 60 -s`
         echo "$GHA_DEPLOY_KEY" | ssh-add -
         mkdir -p ~/.ssh/
         ssh-keyscan github.com >> ~/.ssh/known_hosts
         git push
         ssh-agent -k
