name: gfwlist_auto
 
on:
  [push, workflow_dispatch]

jobs:
  sr_ge:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: sr
        run: python shadowRocket.py
      - name: base64
        run: openssl base64 -in gfwlist_raw.txt | tr -d '\r' > gfwlist.txt
